name: Creating the PR to update the version of buildpacks/github-actions on buildpacks/staging-registry-index
on:
  release:
    types: [published]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISTRIBUTION_TOKEN }}
          repository: buildpacks/staging-registry-index
          event-type: release-event